language: c

os:
  - linux
  - osx

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - texlive
      - texinfo
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
      description: MATLAB MAT File I/O Library
    notification_email: $COVERITY_SCAN_EMAIL
    build_command: make
    branch_pattern: coverity_scan

compiler:
  - gcc-4.8
  - clang

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "C2T0NCiqo98RZXaBTqSWpxcpKhAryOD9VcZ02keuyOPCeNpaLKeo36R/8iAhHWvQddU3V9x0H8EHGN4QY78I1kH3OTwTsGueyRTjKvBsrWlR88pO0CJ33MXz9IvpVE32zACKt2Ltj2GBIUzl0Nm6uwjJXW59pL/86X9ShHK/+hs8Trqu3Zm8MiWg0z79xZzHo+9m7RXW0i5jwxBfIbW15GIMc1TMZC31eHBDjQRCTL89IZzJXVf1ZCd+OsUpvuOVneAl9ihvqyZ3fkK/8n7iVr3TzJDIpj4I3AgVSdg6D0vNsW5HE/czZKTHs6yVI/ImcpPnyApd85MKxjkyppDi3WTBvWn4MkPDMxj1ZJzDQ+0tGIcfaQn9uXiwZCIIezodFK5aY8/OoK9/cVRfjHjZrXkv+hfH0Xys9DrlhSKpeusU0hAS2yoz10g+aN/Sz4fGeRlGrvU0HIncFdXLsD30v7LDTZn4dBIH7C+xE6pbcQ7Y3bGEC3CyR0UbFCbjY20JPMa0k7FBmLRpBUHn9mxJ/eJSnWH/ZI4YRWyJd5fAQvUPvY+5oP+IaEo0oZgSelEUnEssmySFFrVN4YC1GJb63AT7tLPnhgghmzSZUMG/l7Zj0++TEQv+OhtVg8E57iSV0l7WXXwapCyjbFHvjPEwvgZ3plc9XOo+HqYxeHtkx40="
    # COVERITY_SCAN_EMAIL
    - secure: "Qux4CPWkAXdpWPbUwqKTtimTU/xKC2oLtqzH5oMYuTUqyAX9D6XAEx+lq5ADNk5UAQuq4kCWYxPyNOu85vZPV/9INBZ9sSJ+Y5cbQLpJ6nqY7nQHuL5WoIHDtyabgo3mKlsY4mkpM0qcHgHib98/j7vG573pBfp4ihcUu5eKUNxlP07nUILeBPpuJz5GWoCzikU9M0tgjwmydWoa+dJ726HPoPjsu2VY1RFov63u+BWX/c3FUTWyleGVIsQbQeQUcIjMMtHyv0r3wqdsryk88m1rEpDrAy60fki71lcfGuxhzgkSMLezFu2Qj8EqtUrC+Xh4/VIFdn3XbR527OrTQrkJYDelZvEQSoEd3NgiWu5A0R+Zr68YJLjPHoW4TJFj0AG7Nek9bBr27CJOMjAzBVp8FMcVl3/6ApfJb0R89vslPA0J+p/UJdmjhuriiigojMwJQwESpRLtp+oietfr2UtQUeMc9AqCZf4jRzNK4ooEC75Z9MM2FFiuDLhAyYsCwwHrHilXHCCStdjs1jk7YV1+AyU5HIokAYPXjWwxT5BWSIc5wfnIj4lGdMhzJien8/qjyU6kQPiikorKTgd2eD6KzQULuccPudnN9lK6eT+DY4LZ3rfSMGFkMA72w0nmEK4sTGuT8zMC9KS0hgat5b8mzSJ3xhaXig3gQXkrYZk="
    - CPPFLAGS="-DNDEBUG"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - svn co -q https://svn.hdfgroup.uiuc.edu/hdf5/branches/hdf5_1_8_16@28320
  - cd hdf5_1_8_16
  - ./configure --quiet --enable-shared --enable-production --enable-debug=no --with-pic --disable-deprecated-symbols --disable-hl --with-default-api-version=v18 CFLAGS="-O3 -w"
  - make
  - make install
  - cd $TRAVIS_BUILD_DIR

before_script:
  - ./autogen.sh
  - ./configure --quiet --enable-shared --enable-mat73 --enable-extended-sparse --with-pic --with-hdf5=$TRAVIS_BUILD_DIR/hdf5_1_8_16/hdf5 CFLAGS="-O3"

script:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then make; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then make check; fi

after_success:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make pdf; fi

notifications:
  email: false

sudo: required
